name: "KPI"
tags: ["KPI", "Raw"]

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /realpixel/output/*
    fields:
      realpixel_id: ${RP_ID:default_realpixel_id}
      realpixel_region: ${RP_REGION:default_realpixel_region}

output.logstash:
  hosts: ["logstash:5044"]
  worker: 2
  index: filebeat

setup.kibana.host: "kibana:5601"
setup.dashboards.enabled: true

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644
    rotateeverybytes: 10485760 # = 10MB

