name: "KPI"
tags: ["KPI", "Raw"]

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /test/test.*.log
    fields:
      realpixel_id: ${RP_ID:default_realpixel_id}
      realpixel_region: ${RP_REGION:default_realpixel_region}

processors:


output.logstash:
  hosts: ['${LOGSTASH_HOSTS}']
  loadbalance: true
  worker: 2
  index: filebeat

setup.kibana.host: ${KIBANA_HOSTS}
setup.dashboards.enabled: true

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644
    rotateeverybytes: 10485760 # = 10MB

